Profbeats/Profbeats/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
"""Notes from
Vince: We're going to try to run most of our urls directly through this file. Features that have SUB url's can be hashed out in future meetings."""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recommend/', views.recommend, name='recommend'),
    path('recommend_helper/', views.recommend_get, name='recommend_helper'),
    path('messager/', include('messager.urls')),
    path('search/', include('advanced.urls')),
    path('', views.lander_get, name='lander_get'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/register/',views.register_request,name='register'),
    path('playlistContent/<playlistId>',views.updatePlaylistContent,name='content_display'),
    path('profile/playlist/createPlaylist/',views.createPlaylist,name='create_playlist'),
    path('recent/',views.addToPlaylist,name='recent'),
    path('profile/', views.profile, name='profile'),
    path('profile/playlists/<playlistId>', views.updatePlaylist,name='playlist_edit'),
    path('profile/messagefriend/<friendId>', views.messageFriend,name='message_friend'),
    path('profile/deletefriend/<friendId>', views.deleteFriend,name='delete_friend'),
    path('profile/accept/<FRId>', views.acceptFriendRequest,name='accept_friend_request'),
    path('profile/deny/<FRId>', views.denyFriendRequest,name='deny_friend_request'),

    #path('home/', INCOMPLETE PATH),
    #path('search/', INCOMPLETE PATH), #this will probably have a subpage for search/advanced, but both of them can redirect to plain old searchresults/
    #path('searchresults/', INCOMPLETE PATH),
]

Profbeats/advanced/urls.py
from django.urls import path
from . import views

#app_name = 'advanced'

urlpatterns = [
    
    path('advanced_search/', views.advanced_get, name='advsearch'),
    path('advanced_results/', views.advanced_post, name='results'),
    path('search_results/', views.omni_get, name='omniresults'),
    
]
 

Profbeats/messager/urls.py
from django.urls import path
from . import views

app_name = 'messager'

urlpatterns = [
    path('messages/', views.messages, name='messages'),
    path('deletemessage/<message_id>', views.deletemessage, name='deletemessage'),
    path('writemessage/', views.writemessage, name='writemessage'),
    path('writemessage/<recipient>/', views.writemessage, name='writemessage_r'),
    path('writemessage/<recipient>/<subject>/', views.writemessage, name='writemessage_rs'),
]
 

Profbeats/Profbeats/forms.py
# from socket import fromshare
from django import forms
from users.models import CustomUser as User
import users.forms as uforms
from .models import Comment, PRating,Playlist, TPR_Meta, TRating, Track
# NOTE: SOME MODELS MAY NEED TO BE IMPORTED DIRECTLY

class NewUserForm(uforms.UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)
    
class TrackForm(forms.Form):
    aggRating=forms.FloatField(max_value=5.0,min_value=0.0,initial=0.0)
    class Meta:
        model=Track
        fields=('URLId','aggRating')

class PlaylistForm(forms.ModelForm):
    title="Untitled"
    #img=DEFAULT IMAGE HERE
    aggRating=forms.FloatField(max_value=5.0,min_value=0.0,initial=0.0)
    class Meta:
        model=Playlist
        fields=('title','spotify_link','img','owner')

class EditPlaylistForm(forms.Form):
    track=forms.CharField(required=False)
    title=forms.CharField(required=False)
    playlistId=forms.IntegerField()
    img=forms.ImageField(required=False)

class TrackPlaylistRelationForm(forms.ModelForm):
    class Meta:
        model=TPR_Meta
        fields=('playlist','track')

class PlaylistRatingForm(forms.ModelForm):
    class Meta:
        model=PRating
        fields=('rating','prated_by','target')

class TrackRatingForm(forms.ModelForm):
    class Meta:
        model=TRating
        fields=('rating','trated_by','target')

class CommentForm(forms.ModelForm):
    body=forms.CharField(widget=forms.Textarea)
    class Meta:
        model=Comment
        fields=('created_by','name','body')

class ArtistForm(forms.Form):
    artist = forms.CharField(widget=forms.TextInput(attrs={'size': '50'}))
    song1 = forms.CharField(required=False, widget=forms.TextInput(attrs={'size': '50'}))
    song2 = forms.CharField(required=False, widget=forms.TextInput(attrs={'size': '50'}))
    song3 = forms.CharField(required=False, widget=forms.TextInput(attrs={'size': '50'}))
    song4 = forms.CharField(required=False, widget=forms.TextInput(attrs={'size': '50'}))

class FriendRequestForm(forms.Form):
    recipient = forms.CharField(widget=forms.TextInput)

Profbeats/Profbeats/views.py
from faulthandler import dump_traceback
from importlib.machinery import WindowsRegistryFinder
from re import A
from .forms import *
from django.shortcuts import redirect, render,get_object_or_404
from django.http import Http404, HttpResponseRedirect,JsonResponse
from .models import *
from django.views.decorators.http import require_POST, require_GET
import spotipy

from django.shortcuts import render,redirect
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from spotipy.oauth2 import SpotifyClientCredentials
from spotipy.oauth2 import SpotifyOAuth
import random
from spotipy import oauth2
from django.contrib import messages as djangomessages


from django.contrib.auth import logout,login

from spotipy.oauth2 import SpotifyClientCredentials
from spotipy.oauth2 import SpotifyOAuth
import random
from spotipy import oauth2
import spotipy.util as util

cid = '44dbdabeed3d42eba9abf16a4159c53e'
secret = '139765ae1bb445b2abfb6799e1698072'
client_credentials_manager = oauth2.SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

spOAuth = oauth2.SpotifyOAuth(client_id=cid, client_secret=secret, redirect_uri='http://127.0.0.1:8000/')
def find_artists(artist, song1, song2, song3, song4):
	to_pass = 'artist,album,track,playlist,show,episode'
	results = sp.search(q='artist:' + artist, type=to_pass)
	items = results['artists']['items']
	r_tracks = sp.recommendations(seed_artists=[items[0]['id']], seed_tracks=[song1,song2,song3,song4], seed_genres=['rock'])
	temp = r_tracks.get('tracks')
	tracks = []
	for i in range(len(temp)):
		temp2 = temp[i]
		track = temp2.get('id')
		tracks.append(track)
	return tracks

def find_tracks(songs):
	if not songs:
		r_tracks = sp.recommendations(limit=12, min_popularity=79, seed_genres=["acoustic","afrobeat","alt-rock","alternative","ambient"])
	else:
		r_tracks = sp.recommendations(limit=12, seed_tracks=songs)
	temp = r_tracks.get('tracks')
	tracks = []
	for i in range(len(temp)):
		temp2 = temp[i]
		track = temp2.get('id')
		tracks.append(track)
	return tracks

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			profile = UserProfile.objects.create(user=user)
			f_playlist=PlaylistForm(None)
			new_playlist = f_playlist.save(commit=False)
			new_playlist.title="Favorites"
			new_playlist.aggRating=0.0
			new_playlist.image=None
			new_playlist.owner=user
			new_playlist.save()
			f2_playlist=PlaylistForm(None)
			new2_playlist = f2_playlist.save(commit=False)
			new2_playlist.title="Recents"
			new2_playlist.aggRating=0.0
			new2_playlist.image=None
			new2_playlist.owner=user
			new2_playlist.save()
			profile.favorites=new_playlist
			profile.recents=new2_playlist
			profile.save()
			login(request, user)
			djangomessages.success(request, "Registration successful." )
			return redirect('lander_get')
		djangomessages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request, 'signup.html', {"register_form":form})

def loginForm(request):
	form = LoginForm()
	return render(request, 'login.html', {'form': form})

def logout_view(request):
	logout(request)
	return redirect('lander_get')

def createPlaylist(request):
	f_playlist = PlaylistForm(request)
	new_playlist = f_playlist.save(commit=False)
	new_playlist.title="Untitled"
	new_playlist.aggRating=0.0
	new_playlist.image=None
	new_playlist.owner=request.user
	new_playlist.tracks=None
	new_playlist.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def addToPlaylist(request):
	if request.method == 'POST':
		addForm = EditPlaylistForm(request.POST)
		if addForm.is_valid():
			track = addForm.cleaned_data['track']
			playlistId = addForm.cleaned_data['playlistId']
			newTrack,created=Track.objects.get_or_create(id=track,aggRating=0.0)
			print("Data is: ", newTrack,created,playlistId)
			if created:
				newTrack.save()
			Playlist.objects.get(pk=playlistId).tracks.add(newTrack)
		else:
			raise Http404('Invalid Form Error',addForm.data)
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def updatePlaylist(request,playlistId):
	playlist = Playlist.objects.get(pk=playlistId)
	context = {
		'comments': playlist.comments.all(),
		'content': playlist.tracks.all(),
		'playlist': playlist
	}
	if request.method == 'GET':
		form = EditPlaylistForm(playlist)
		context['form'] = form
		return render(request,'createPlaylist.html',context)
	if request.method == 'POST':
		form = EditPlaylistForm(request.POST)
		uPlaylist = None
		if form.is_valid():
			if 'rename' in request.POST:
				uPlaylist = Playlist.objects.get(pk=playlistId).update(title=form.title)
			if 'resplash' in request.POST:
				uPlaylist = Playlist.objects.get(pk=playlistId).update(img=form.img)
			if 'dropTrack' in request.POST:
				uPlaylist = Playlist.objects.get(pk=playlistId).remove(form.track)
			uPlaylist.save()
		else:
			raise Http404('Invalid Form Error')
		context['form'] = form
		return render(request,'createPlaylist.html',context)

### Universal Handler Function for the playlistContent.html webpage ###
def updatePlaylistContent(request,playlistId):
	playlist=Playlist.objects.get(pk=playlistId)
	f_comment = CommentForm(None)
	f_prate = PlaylistRatingForm(None)
	f_trate = TrackRatingForm(None)

	if request.method == 'POST':
		if 'post_comment' in request.POST:
			f_comment = CommentForm(request.POST)
			new_comment=None
			if f_comment.is_valid():
				new_comment=f_comment.save(commit=False)
				new_comment.playlist=playlist
				new_comment.save()
			else:
				raise Http404('Comment Failed to Post')
		if 'rate_playlist' in request.POST:
			f_prate = PlaylistRatingForm(request.POST)
			if f_prate.is_valid():
				f_prate.save()
		if 'rate_track' in request.POST:
			f_trate = TrackRatingForm(request.POST)
			if f_trate.is_valid():
				f_trate.save()

	### REFERENCE KEY FOR FRONTEND VARIABLES ###
	### You can access ALL FIELDS of playlist using playlist.fieldname in .html! ###
	context = {
		'f_comment':f_comment,
		'f_prate':f_prate,
		'f_trate':f_trate,
		'content':playlist.tracks.all(),
		'comments':playlist.comments.all(),
		'playlist':playlist,
	}
	return render(request,'playlistContent.html',context)


@require_POST
def recommend(request):
	form = ArtistForm(request.POST)
	if form.is_valid():
		song1 = None if form.cleaned_data['song1'] == None else form.cleaned_data['song1']
		song2 = None if form.cleaned_data['song2'] == None else form.cleaned_data['song2']
		song3 = None if form.cleaned_data['song3'] == None else form.cleaned_data['song3']
		song4 = None if form.cleaned_data['song4'] == None else form.cleaned_data['song4']
		tracks = find_artists(form.cleaned_data['artist'], song1, song2, song3, song4)
		return render(request, 'recommender/searchformRecommendations.html', {'form': form, 'tracks':tracks })
	else:
		raise Http404('Something went wrong')

@require_GET
def recommend_get(request):
	form = ArtistForm()
	return render(request, 'recommender/searchformRecommendations.html', {'form': form})


def lander_get(request):
	tracksall = []
	addForm=EditPlaylistForm(None)
	# print(request.user.profile.recents.spotify_link[34:])
	if not request.user.is_authenticated:
		tracks = find_tracks([])
		for i in range(0, 1000, 4):
			tracksall.append(tracks[i:i+4])
		return render(request, 'lander.html', {'tracksall': tracksall, 'not_logged_in': True})
	elif len(request.user.profile.recents.tracks.all()) == 0:
		tracks = find_tracks([])
		for i in range(0, 1000, 4):
			tracksall.append(tracks[i:i+4])
		return render(request, 'lander.html', {'tracksall': tracksall, 'recently_listened_to': [], 'addForm':addForm})
	recently_listened_to_tracks = list(request.user.profile.recents.tracks.all().values_list('id',flat=True))
	temp = recently_listened_to_tracks
	if len(recently_listened_to_tracks) < 5:
		recently_listened_to_tracks = recently_listened_to_tracks[::-1]
	else:
		recently_listened_to_tracks = recently_listened_to_tracks[(len(recently_listened_to_tracks)-4)::]
	recently_listened_to_tracks.reverse()
	tracks = find_tracks(recently_listened_to_tracks)
	for i in range(0, 1000, 4):
		tracksall.append(tracks[i:i+4])
	if not temp:
		return render(request, 'lander.html', {'tracksall': tracksall, 'addForm':addForm})
	return render(request, 'lander.html', {'tracksall': tracksall, 'recently_listened_to': recently_listened_to_tracks, 'addForm':addForm})

token = util.prompt_for_user_token(username='9indqdxoj2o45azyfw4ebz5ux',scope='playlist-modify-private',client_id='44dbdabeed3d42eba9abf16a4159c53e',client_secret='139765ae1bb445b2abfb6799e1698072', redirect_uri='http://127.0.0.1:8000/')
def recent(request, track):
	print("HERE TRACK", track)
	if token:
		print("HERE TOKEN")
		sp2 = spotipy.Spotify(auth=token)
		if not request.user.profile.recents:
			request.user.profile.recents = Playlist()
		recents = request.user.profile.recents.playlistId
		playlist = sp2.playlist(recents)
		for item in playlist['tracks']['items']:
			if len(playlist['tracks']['items']) > 4:
				sp2.playlist_remove_specific_occurrences_of_items(playlist_id=recents, items=[{'uri': item['track']['id'], 'positions': [0]},])
			break
		addPlaylist = Playlist.objects.get(pk=playlist.playlistId).add(f_TPR.track)
		addPlaylist.save()
		sp2.playlist_add_items(playlist_id=recents, items=[track])

	return redirect("lander_get")

def profile(request):
	# You need to be logged in to view your profile.
	# Redirect to the login page if the user is not logged in.
	if not request.user.is_authenticated:
		djangomessages.warning(request, ("You need to be logged in to view your profile."))
		return redirect('login')

	context = {}
	form = FriendRequestForm()
	if request.method == 'POST':
		form = FriendRequestForm(request.POST)
		if form.is_valid():
			formrecipient = form.cleaned_data['recipient']

Profbeats/Profbeats/templates/createPlaylist.html
{% extends 'base.html' %}
{% block content %}



{%endblock%}

Profbeats/Profbeats/templates/favorites.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <body>
        <div>
            <br/>
            <div class="playlistObject">
                <img src="{% static 'Profbeats/images/midnightprom.jpg' %}" class="img-fluid">
                <br/>
                <!-- Should say "Favorites" -->
                Title: {{ playlist.title }}
            </div>
        <br/>
        </div>
        <table class="table">
            <tbody>
                <tr>
                    {% for song in content %}
                    <td>
                        <iframe src="https://open.spotify.com/embed/track/{{ song.id }}" width="400" height="100"
                            frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                        <br>
                    </td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
    <table class="table">
        <tbody>
            <tr>
                {% for song in content %}
                    <td>
                        <iframe src="https://open.spotify.com/embed/track/{{ song.id }}" width="400" height="100"
                        frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                    </td>
                {% endfor %}
            </tr>
        </tbody>
    </table>
    {% for comment in comments %}
    <div class="comment" style="padding: 10px;">
        <p class="font-weight-bold">
            {{comment.created_by}}
            <span class="text-muted font-weight-normal">
                {{comment.created_on}}
            </span>
        </p>
        {{comment.body|linebreaks}}
    </div>
    {% endfor %}
    
    <br/>
</body>

{%endblock%}

        <style>
            * {
                font-size: 20px;
            }

            .playlistObject {
                font-weight: bold;
                font-size: 25px;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-direction: column;
            }

            .checked {
                color: orange;
            }
        </style>

{%endblock%}

Profbeats/Profbeats/templates/lander.html
{% extends 'base.html' %}

{% block title %} ProfBeats {% endblock %}

{% block content %}
{% load static %}

<div id="mainpage">
    <div id="welcomeRow">
        {% if not user.is_authenticated %}
        <h1>Welcome to Profbeats, log in to listen to personally recommended songs</h1>
        {% else %}
        <h1>Welcome to Profbeats, {{ user }}</h1>
        {% endif %}
    </div>

    <!-- <div id="firstRow">
        <div id="row1left">
            <h4>See what everyone's listening to.</h4>
            <p>Check out trending albums, artists, etc.</p>
            <button type="button" class="btn btn-dark">Check it out</button>
        </div>

        <div id="row1right">
            <!-- Slideshow container
            <div class="slideshow-container">

                <!-- Full-width images with number and caption text
                <div class="mySlides fade">
                <div class="numbertext">1 / 3</div>
                <img src="dawnfm.jpeg" style="width:25vw; height:25vw">
                <div class="text-secondary">Dawn FM - The Weeknd</div>
                </div>
            
                <div class="mySlides fade">
                <div class="numbertext">2 / 3</div>
                <img src="youngblood.png" style="width:25vw; height:25vw">
                <div class="text-secondary">Youngblood - 5 Seconds of Summer</div>
                </div>
            
                <div class="mySlides fade">
                <div class="numbertext">3 / 3</div>
                <img src="am.jpeg" style="width:25vw; height:25vw">
                <div class="text-secondary">AM - Arctic Monkeys</div>
                </div>
            
                <!-- Next and previous buttons
                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" onclick="plusSlides(1)">&#10095;</a>
            </div>
            <br>
            
            <!-- The dots/circles
            <div style="text-align:center">
                <span class="dot" onclick="currentSlide(1)"></span>
                <span class="dot" onclick="currentSlide(2)"></span>
                <span class="dot" onclick="currentSlide(3)"></span>
            </div>
            
        </div>

        <!--
        <div>
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                <div class="carousel-item active">
                        <img src="dawnfm.jpeg" class="d-block w-100" alt="Dawn FM by The Weeknd">
                </div>
                <div class="carousel-item">
                        <img src="youngblood.png" class="d-block w-100" alt="Youngblood by 5 Seconds of Summer">
                </div>
                <div class="carousel-item">
                        <img src="am.jpeg" class="d-block w-100" alt="AM by Arctic Monkeys">
                </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <script language="JavaScript" type="text/javascript">
            $(document).ready(function(){
            $('.carousel').carousel({
                interval: 2000
            })
            });    
        </script>
        
    </div>
    -->

    <br/><br/><br/>

    <div id="recommendRow">
        {% if not recently_listened_to %}
            {% if not user.is_authenticated %}
            <h1>Check out what's popular</h1>
            <table class="table">
                <tbody>
                {% for tracks in tracksall %}
                <tr>
                {% for track in tracks %}
                <td>
                <iframe src="https://open.spotify.com/embed/track/{{ track }}" width="300" height="380" 
                frameborder="10" allowtransparency="true" allow="encrypted-media"></iframe>
                </td>
                {% endfor %}
                </tr>
                {% endfor %}
                </tr>
                </tbody>
                </table>
        {% else %}
        <h1>Check out what's popular</h1>
        <table class="table">
            <tbody>
            {% for tracks in tracksall %}
            <tr>
            {% for track in tracks %}
            <td>
            <iframe src="https://open.spotify.com/embed/track/{{ track }}" width="300" height="380" 
            frameborder="10" allowtransparency="true" allow="encrypted-media"></iframe>
            <form method="POST" action="{% url 'recent' %}">
                {% csrf_token %}
                <input type="hidden" name="track" value="{{ track }}">
                <input type="hidden" name="playlistId" value="{{ user.profile.recents.id }}">
                <input type="hidden" name="test" value="{{ user }}">
                <button class="btn btn-dark btn-lg" type="submit" name="addRecent">Add to Recents</button>
            </form>
            </td>
            {% endfor %}
            </tr>
            {% endfor %}
            </tr>
            </tbody>
            </table>
            {% endif %}
        {% else %}
        {% if tracksall %}
        <table class="table">
        <tbody>
        <tr>
        <h1>Because you listened to: </h1>
        {% for track in recently_listened_to %}
        <td>
        <iframe src="https://open.spotify.com/embed/track/{{ track }}" width="300" height="380" 
        frameborder="10" allowtransparency="true" allow="encrypted-media"></iframe>
        </td>
        {% endfor %}
        </tr>
        </tbody>
        </table>
        <table class="table">
        <tbody>
        <h1>You may like: </h1>
        {% for tracks in tracksall %}
        <tr>
        {% for track in tracks %}
        <td>
        <iframe src="https://open.spotify.com/embed/track/{{ track }}" width="300" height="380" 
        frameborder="10" allowtransparency="true" allow="encrypted-media"></iframe>
        <form method="POST" action="{% url 'recent' %}">
            {% csrf_token %}
                <input type="hidden" name="track" value="{{ track }}">
                <input type="hidden" name="playlistId" value="{{ user.profile.recents.id }}">
                <input type="hidden" name="test" value="{{ user }}">
                <button class="btn btn-dark btn-lg" type="submit" name="addRecent">Add to Recents</button>
        </form>
        </td>
        {% endfor %}
        </tr>
        {% endfor %}
        </tr>
        </tbody>
        </table>
        {% endif %}
        {% endif %}
    </div>

    <div id="secondRow">
        <div class="row2boxes" id="row2left">
            <img src="{% static 'Profbeats/images/headphonesIcon.png' %}" class="row2Icons" alt="Icon - headphones">
            <br/>
            <h4 class="row2textHead">Listen to all the new stuff</h4>
            <p class="row2textBody">See what everyone is listening to now</p>
        </div>
        <div class="row2boxes" id="row2right">
            <img src="{% static 'Profbeats/images/convoIcon.png' %}" class="row2Icons" alt="Icon - conversation">
            <br/>
            <h4 class="row2textHead">Converse with like-minded audiophiles</h4>
            <p class="row2textBody">Talk to our community and join the conversation</p>
        </div>
    </div>

    <div id="thirdRow">
        <div class="row3boxes" id="row3left">
            <img src="{% static 'Profbeats/images/image.png' %}" id="comingsoonlogo" alt="ProfBeats Logo">
        </div>
        <div class="row3boxes" id="row3right">
            <h3>Great changes are coming</h3>
            <p>Here's what we have in store for our web app</p>
            <button type="button" class="btn btn-dark">New Stuff</button>
        </div>
    </div>
</div>

<br/>
{% endblock %}

Profbeats/Profbeats/templates/profile.html
{% extends 'base.html' %}

{% block title %} ProfBeats | Profile {% endblock %}

{% block content %}
<br>
<center><h1>Profile of {{ request.user }}</h1></center>
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissable" role="alert">
            <button class="close" data-dismiss="alert">
                X
            </button>
            <center>{{ message }}</center>
        </div>
        {% else %}
        <div class="alert alert-warning" role="alert">
            <center>{{ message }}</center>
        </div>
        {% endif %}
    {% endfor %}
{% endif %}
<div class="container">
    <form method='post' action="/profile/">
        {% csrf_token %}
        <h2>Find a Friend by Email</h2>
        <br>
        <div>
            Recipient: {{ form.recipient }}
        </div>
        <br>
        <button class="btn btn-primary btn-lg" type="submit">Send Friend Request</button>
    </form>
</div>
<br>

{% if friend_request_list %}
<center><h2>Pending Friend Requests</h2></center>
<table class="table table-striped">
    <thead>
        <tr>
          <th scope="col">Email</th>
          <th></th>
          </tr>
        </thead>
        <tbody>
    {% for fr in friend_request_list %}
      <tr>
        <td>{{ fr.sender }}</td>
        <td colspan="2" class="text-right"><a class="btn btn-success" href="{% url 'accept_friend_request' fr.id %}">Accept</a>
          <a class="btn btn-danger" href="{% url 'deny_friend_request' fr.id %}">Deny</a></td>
      </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}

<center><h2>Friend List</h2></center>
{% if request.user.profile.friendList.exists %}
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
    {% for friend in request.user.profile.friendList.all %}
      <tr>
        <td>{{ friend }}</td>
        <td class="text-right"><a class="btn btn-secondary" href="{% url 'messager:writemessage_r' friend.get_username %}">Send a Message</a>
          <a class="btn btn-danger" href="{% url 'delete_friend' friend.id %}">Delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
<center><h6>Your friend list is empty!</h6></center>
{% endif %}
<br>
{% for playlist in playlists %}
<table>
  <tr>
    <td>{{ playlist.title }}</td>
    <td><a class="btn btn-secondary" href="{% url 'playlist_edit' playlist.id %}">Edit Playlist</a></td>
  </tr>
</table>
{% endfor %}
{% endblock %}